/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MainHomeRouteImport } from './routes/_main/home'
import { Route as MainArchivedRouteImport } from './routes/_main/archived'
import { Route as AuthAuthRouteRouteImport } from './routes/auth/_auth/route'
import { Route as AuthAuthSignUpRouteImport } from './routes/auth/_auth/sign-up'
import { Route as AuthAuthSignInRouteImport } from './routes/auth/_auth/sign-in'
import { Route as AuthAuthResetPasswordRouteImport } from './routes/auth/_auth/reset-password'
import { Route as AuthAuthForgotPasswordRouteImport } from './routes/auth/_auth/forgot-password'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainHomeRoute = MainHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainArchivedRoute = MainArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => MainRouteRoute,
} as any)
const AuthAuthRouteRoute = AuthAuthRouteRouteImport.update({
  id: '/auth/_auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthSignUpRoute = AuthAuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthAuthRouteRoute,
} as any)
const AuthAuthSignInRoute = AuthAuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthAuthRouteRoute,
} as any)
const AuthAuthResetPasswordRoute = AuthAuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthAuthRouteRoute,
} as any)
const AuthAuthForgotPasswordRoute = AuthAuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthAuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthAuthRouteRouteWithChildren
  '/archived': typeof MainArchivedRoute
  '/home': typeof MainHomeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/forgot-password': typeof AuthAuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthAuthResetPasswordRoute
  '/auth/sign-in': typeof AuthAuthSignInRoute
  '/auth/sign-up': typeof AuthAuthSignUpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthAuthRouteRouteWithChildren
  '/archived': typeof MainArchivedRoute
  '/home': typeof MainHomeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/forgot-password': typeof AuthAuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthAuthResetPasswordRoute
  '/auth/sign-in': typeof AuthAuthSignInRoute
  '/auth/sign-up': typeof AuthAuthSignUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_main': typeof MainRouteRouteWithChildren
  '/auth/_auth': typeof AuthAuthRouteRouteWithChildren
  '/_main/archived': typeof MainArchivedRoute
  '/_main/home': typeof MainHomeRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/_auth/forgot-password': typeof AuthAuthForgotPasswordRoute
  '/auth/_auth/reset-password': typeof AuthAuthResetPasswordRoute
  '/auth/_auth/sign-in': typeof AuthAuthSignInRoute
  '/auth/_auth/sign-up': typeof AuthAuthSignUpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/archived'
    | '/home'
    | '/api/auth/$'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/archived'
    | '/home'
    | '/api/auth/$'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
  id:
    | '__root__'
    | '/'
    | '/_main'
    | '/auth/_auth'
    | '/_main/archived'
    | '/_main/home'
    | '/api/auth/$'
    | '/auth/_auth/forgot-password'
    | '/auth/_auth/reset-password'
    | '/auth/_auth/sign-in'
    | '/auth/_auth/sign-up'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRouteRoute: typeof MainRouteRouteWithChildren
  AuthAuthRouteRoute: typeof AuthAuthRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/home': {
      id: '/_main/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof MainHomeRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/archived': {
      id: '/_main/archived'
      path: '/archived'
      fullPath: '/archived'
      preLoaderRoute: typeof MainArchivedRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/auth/_auth': {
      id: '/auth/_auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/_auth/sign-up': {
      id: '/auth/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthAuthSignUpRouteImport
      parentRoute: typeof AuthAuthRouteRoute
    }
    '/auth/_auth/sign-in': {
      id: '/auth/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthAuthSignInRouteImport
      parentRoute: typeof AuthAuthRouteRoute
    }
    '/auth/_auth/reset-password': {
      id: '/auth/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthAuthResetPasswordRouteImport
      parentRoute: typeof AuthAuthRouteRoute
    }
    '/auth/_auth/forgot-password': {
      id: '/auth/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthAuthForgotPasswordRouteImport
      parentRoute: typeof AuthAuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MainRouteRouteChildren {
  MainArchivedRoute: typeof MainArchivedRoute
  MainHomeRoute: typeof MainHomeRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainArchivedRoute: MainArchivedRoute,
  MainHomeRoute: MainHomeRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface AuthAuthRouteRouteChildren {
  AuthAuthForgotPasswordRoute: typeof AuthAuthForgotPasswordRoute
  AuthAuthResetPasswordRoute: typeof AuthAuthResetPasswordRoute
  AuthAuthSignInRoute: typeof AuthAuthSignInRoute
  AuthAuthSignUpRoute: typeof AuthAuthSignUpRoute
}

const AuthAuthRouteRouteChildren: AuthAuthRouteRouteChildren = {
  AuthAuthForgotPasswordRoute: AuthAuthForgotPasswordRoute,
  AuthAuthResetPasswordRoute: AuthAuthResetPasswordRoute,
  AuthAuthSignInRoute: AuthAuthSignInRoute,
  AuthAuthSignUpRoute: AuthAuthSignUpRoute,
}

const AuthAuthRouteRouteWithChildren = AuthAuthRouteRoute._addFileChildren(
  AuthAuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRouteRoute: MainRouteRouteWithChildren,
  AuthAuthRouteRoute: AuthAuthRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
